version: '3'

services:
  galaxy:
    container_name: "postman"
    image: dollarkiller/postman:latest
    restart: always
    environment:
      RocketChatAddr: "" # http://xxx/api/v1/chat.postMessage
      RocketChatToken: ""
      RocketChatUserID: ""
      WorkWechatAgentID: ""
      WorkWechatCorpID: ""
      WorkWechatCorpSecret: ""
      PostmanAddr: "0.0.0.0:8675"
      PostmanToken: "PostmanToken"
    ports:
      - "8675:8675"
